### ISSUE TITLE
真の 64 ビット MSIX 化

### ISSUE THREAD

**Issue by shinta0806** [shinta0806/YukaListerNebula#138]
真の 64 ビット MSIX 化して欲しいです。

［対応状況］検討中
［報告経路］SHINTA

**Comment by shinta0806** [comment]
（メモ）
現状、 https://shinta0806be.ldblog.jp/archives/10470683.html の対策によりビルドはできるものの、実行すると以下のエラーになってしまう。

スプラッシュウィンドウ初期化時エラー：
The type initializer for 'YukaLister.Models.YukaListerModels.YukaListerModel' threw an exception.
   at YukaLister.Models.YukaListerModels.YukaListerModel.get_Instance() in D:\DevProject\VisualStudio\Projects\YukaListerNebula\Src\Models\YukaListerModels\YukaListerModel.cs:line 22
   at YukaLister.ViewModels.SplashWindowViewModel.Initialize() in D:\DevProject\VisualStudio\Projects\YukaListerNebula\Src\ViewModels\SplashWindowViewModel.cs:line 89

**Comment by shinta0806** [comment]
Ver 6.15 にて対応完了しました。
